### ISSUE TITLE
关于表单校验

### ISSUE THREAD

**Issue by magicianCoder** [kdcloudone/kdesign#13]
当表单某个字段的值不为字符串时就会触发界面校验异常，比如对于必录校验，当字段值变为非字符串类型(如数字、数组)，就会提示字段必录错误；但是使用 form.validateFields 不会有异常。

**Comment by hxh2010** [comment]
> 当表单类型错误的值不为异常时，比如字符串会触发显示校验，当数字字段变成非字符串类型（如、类型）时，会提示字段必录错误；但是使用 form.validateFields 不会有异常。

可否描述下具体场景或贴出代码
