### ISSUE TITLE
table组件拖拽列排序bug

### ISSUE THREAD

**Issue by lqstone** [kdcloudone/kdesign#209]
## 重现链接或代码
const _columns = [
    { code: 'No', name: '序号', width: 60, align: 'center' },
    { code: 'order', name: '单据号', width: 200, hidden: true},
    { code: 'from', name: '来户', width: 200, hidden: true },
    { code: 'to', name: '往户', width: 200, hidden: true },
    { code: 'amount', name: '应付金额', width: 100, align: 'right',  },
    { code: 'balance', name: '应收余额', width: 100, align: 'right',  }
  ]

## 重现问题步骤
在 _columns 中列添加 hidden 为 true 的设置，再次拖拽列进行排序，会出现空白占位，动作不流畅，感觉中间还是有隐藏的列在占位。

## 期望的结果是什么
能够正常拖拽排序不卡顿不空白。

## 实际的结果是什么
卡顿空白列出现

## 组件库版本号、浏览器信息
最新版，chrome

**Comment by wqhui** [comment]
`column.hidden`已经是将要废弃的属性，开发时有对应的警告，所以该问题暂不处理，感谢反馈~
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/16059309/217415233-3b607d4c-0079-4d16-92c1-5243cbed2551.png">

**Comment by lqstone** [comment]
你们这直接干掉hidden解决问题，我们业务需求是需要隐藏功能的，列设置需要进行显示隐藏换位配置，不可能去动态增减数组项啊。

**Comment by wqhui** [comment]
这里是我们疏忽把该属性暴露到文档上了，这个警告是一直都存在的，我们这边也参考了类似的组件库，都没有提供类似的属性，这里可以在传入`Table`的`columns` 属性时过滤一下列数组即可，不用修改原始数组，eg:
```js
function isLeafNode (node) {
  return node.children == null || node.children.length === 0
}
function filterHideColumn(columns: ArtColumn[],) {
  function dfs(columns: ArtColumn[]): ArtColumn[] {
    const result: ArtColumn[] = []

    for (let column of columns) {
      if (isLeafNode(column)) {
        if (column.hidden) {
          // 被隐藏的列 会在这里被剔除
        } else {
          result.push(column)
        }
      } else {
        const nextChildren = dfs(column.children)
        // 如果 nextChildren 为空，说明所有的子节点均被隐藏了，在这里隐藏父节点
        if (nextChildren.length > 0) {
          result.push({ ...column, children: nextChildren })
        }
      }
    }
    return result
  }

  return dfs(columns)
}

<Table columns={filterHideColumn(columns)}>
```
