### ISSUE TITLE
table 组件，树形数据展示，希望提供 全部展开 和 全部收起 的功能。

### ISSUE THREAD

**Issue by lqstone** [kdcloudone/kdesign#210]
## 期望的结果是什么
希望有提供全部展开和全部收起的功能个

**Comment by wqhui** [comment]
你好，目前表格使用react的思路开发，提供受控的属性`openKeys`，来控制展开收起的行：
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/16059309/222322716-4b2a2b47-8545-4e79-ae6e-155438eb1e6f.png">

用户可以使用该种方式自己控制展开或者收起的行
