### ISSUE TITLE
table 组件，希望增加列单元格hover显示title的配置

### ISSUE THREAD

**Issue by lqstone** [kdcloudone/kdesign#217]
## 期望的结果是什么
列设置增加一个参数，控制是否 hover 显示 title。

**Comment by wqhui** [comment]
你好，请问下列单元格是指哪个部分？是指表头还是表体？

**Comment by lqstone** [comment]
主要是标体需要。

**Comment by lqstone** [comment]
> 你好，请问下列单元格是指哪个部分？是指表头还是表体？

主要是标体需要。

**Comment by wqhui** [comment]
> 主要是标体需要

@lqstone 基础表格不好提供该功能，因为title的值不总是固定的，单元格的显示内容一般都会自定义，所以建议使用`column.getCellProps` 返回title:
```
const columns = [{
  code: 'code',
  name: 'name',
  getCellProps: (value, record,rowIndex)=>({title:value||record['code']})
}]
```
