### ISSUE TITLE
[Table]希望Table表头name | title可以传自定义ReactNode

### ISSUE THREAD

**Issue by huangwei9527** [kdcloudone/kdesign#218]
## 实际的结果是什么

![image](https://user-images.githubusercontent.com/18244110/212404347-d68ac29f-75eb-41b8-9079-b8b23143f8df.png)

**Comment by wqhui** [comment]
感谢反馈，这里`column.title`是支持ReactNode类型的，这里文档有误，我们修改下

**Comment by wqhui** [comment]
目前建议直接用`column.title`修改，`column.name`指的是列的名称，意义不一样
