### ISSUE TITLE
[Tree]自定义展开收起图标鼠标可点击范围太小

### ISSUE THREAD

**Issue by huangwei9527** [kdcloudone/kdesign#236]
## 重现链接或代码
![downloadfile](https://user-images.githubusercontent.com/18244110/217437181-c27ce717-e6d2-42cd-8099-fc292f0962c5.gif)

**Comment by kobehhh** [comment]
自己调整传进去的图标大小就可以了
<img width="861" alt="image" src="https://user-images.githubusercontent.com/33951750/217461329-aa511aac-c539-472f-8fde-57801c591dec.png">
如果图片过大导致被遮挡就要调整一下这两个值
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/33951750/217461868-8265e57e-733a-430e-b785-4291f64f4cb5.png">

**Comment by huangwei9527** [comment]
> 自己调整传进去的图标大小就可以了 <img alt="image" width="861" src="https://user-images.githubusercontent.com/33951750/217461329-aa511aac-c539-472f-8fde-57801c591dec.png"> 如果图片过大导致被遮挡就要调整一下这两个值 <img alt="image" width="1137" src="https://user-images.githubusercontent.com/33951750/217461868-8265e57e-733a-430e-b785-4291f64f4cb5.png">

不是大小的问题，是图标左半边点没反应，只有右边有鼠标点击响应事件
你看动画示例上，鼠标移到到展开收起图标上，鼠标没有变成手型

**Comment by albyben** [comment]
看看window系统下是否能复现该问题 @kobehhh
