### ISSUE TITLE
[ImageCropper] 图片裁剪组件需要支持设置裁剪区域的宽度

### ISSUE THREAD

**Issue by eden-hjh** [kdcloudone/kdesign#270]
## 重现链接或代码
https://react.kingdee.design/components/image-cropper#API

## 期望的结果是什么
裁剪框区域宽度支持配置，期望裁剪框可以填充完整个背景

## 实际的结果是什么
目前只支持宽高比
![image](https://user-images.githubusercontent.com/121602610/221743726-7253fce5-3744-437a-89eb-023e273e4d9f.png)

![image](https://user-images.githubusercontent.com/121602610/221743399-e453583a-d69a-46d1-8d6a-2d97630ff666.png)

## 组件库版本号、浏览器信息
组件库版本：v1.6.36

**Comment by kobehhh** [comment]
新开放api autoCropArea（裁剪区域大小(百分比)）

function Demo() {
  const cropperRef = React.useRef()
  const fn = () => {
    console.log(cropperRef.current.cropper.current) // 查看图片裁剪开放出去的api（https://www.npmjs.com/package/cropperjs）
  }

  return (
    <div style={{ textAlign: 'center' }}>
      <Button onClick={fn}>12 </Button>
      <ImageCropper
        visible={true}
        autoCropArea={1}
        containerWidth={830}
        title="拖拽图片"
        ref={cropperRef}
        image="https://webstatic.mihoyo.com/ys/event/e20210721-fab/images/1.f6ed965b.jpg"
        getContainer={false}
        mask={false}
        dragMode="move"
        cropBoxMovable={false}
      />
    </div>
  )
}

**Comment by kobehhh** [comment]
```jsx
import { ImageCropper, Button } from '@kdcloudjs/kdesign'

function Demo() {
  const cropperRef = React.useRef()
  const fn = () => {
    console.log(cropperRef.current.cropper.current) // 查看图片裁剪开放出去的api（https://www.npmjs.com/package/cropperjs）
  }

  return (
    <div style={{ textAlign: 'center' }}>
      <Button onClick={fn}>12 </Button>
      <ImageCropper
        visible={true}
        autoCropArea={1}
        containerWidth={830}
        title="拖拽图片"
        ref={cropperRef}
        image="https://webstatic.mihoyo.com/ys/event/e20210721-fab/images/1.f6ed965b.jpg"
        getContainer={false}
        mask={false}
        dragMode="move"
        cropBoxMovable={false}
      />
    </div>
  )
}

render(<Demo />)
```
