### ISSUE TITLE
可编辑Table的input输入框不可通过鼠标选择移动光标

### ISSUE THREAD

**Issue by Tshangsl** [kdcloudone/kdesign#277]
## 重现链接或代码

官网
## 重现问题步骤
可编辑Table的input输入框不可通过鼠标选择移动光标

## 期望的结果是什么
可编辑Table的input输入框可以通过鼠标选择移动光标

## 组件库版本号、浏览器信息
1.6.20
85.0.4183.102

**Comment by albyben** [comment]
见pr 38295a6aac315032eb63c562d771c78bd9052a08
