### ISSUE TITLE
【Modal】组件拖拽bug

### ISSUE THREAD

**Issue by lqstone** [kdcloudone/kdesign#291]
## 重现链接或代码
![image](https://user-images.githubusercontent.com/13195110/226619919-100cdee2-dc0e-4459-9dc4-86f71483ce0a.png)

## 重现问题步骤
开启 draggable 功能后，拖拽的时候会拖出挂载 dom 节点的可视区域。

## 期望的结果是什么
限制拖出挂载的dom区域，碰到边界则不可再往外拖动。

**Comment by albyben** [comment]
参见官方`可拖拽demo` 1.7.2版本新添加3个api
![image](https://user-images.githubusercontent.com/22462180/233523518-9aa439f0-9d14-4b3c-89d1-a81a458cf3f8.png)
