### ISSUE TITLE
Modal body 值的问题

### ISSUE THREAD

**Issue by zzkkui** [kdcloudone/kdesign#345]
## Moda body 值的问题
![image](https://github.com/kdcloudone/kdesign/assets/24466870/d44ac5d4-d68d-4ff6-8322-568db09a68bc)
文档描述

但是 body 传值不同，会有问题。

例子1：
```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Button, Modal, Input  } from '@kdcloudjs/kdesign'

function Demo() {
  const bodyStyle = {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }
  const [visible, setVisible] = React.useState(false)
    const [value, setValue] = React.useState('')
  const handleClick = (bool) => {
    setVisible(bool)
  }
  
  const Body = () => {
    return <Input value={value} onChange={(e) => setValue(e.target.value)} />
  }

  return (
    <div className={'test_container'}>
      <Button
        onClick={() => {
          handleClick(true)
        }}>
        基础弹出框
      </Button>
      <Modal
// 这样弹窗不会有问题
   //  body={<>{Body()}</> }
        body={Body()}
        bodyStyle={bodyStyle}
        title="Basic Modal"
        closable={true}
        onCancel={() => handleClick(false)}
        onOk={() => handleClick(false)}
        mask={true}
        visible={visible}
      />
    </div>
  )
}

ReactDOM.render(<Demo />, mountNode)
```

例子2
```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Button, Modal, Input  } from '@kdcloudjs/kdesign'

function Demo() {
  const bodyStyle = {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }
  const [visible, setVisible] = React.useState(false)
    const [value, setValue] = React.useState('')
  const handleClick = (bool) => {
    setVisible(bool)
  }
  
  const Body = () => {
    return <Input value={value} onChange={(e) => setValue(e.target.value)} />
  }

  return (
    <div className={'test_container'}>
      <Button
        onClick={() => {
          handleClick(true)
        }}>
        基础弹出框
      </Button>
      <Modal
// 若是这样传，输入框每次输入都会失焦，猜测是整个 Body 组件被重新渲染了
        body={<Body />}
        bodyStyle={bodyStyle}
        title="Basic Modal"
        closable={true}
        onCancel={() => handleClick(false)}
        onOk={() => handleClick(false)}
        mask={true}
        visible={visible}
      />
    </div>
  )
}

ReactDOM.render(<Demo />, mountNode)
```
事实上这里是 react渲染方式不同，是否考虑增加兼容

**Comment by kobehhh** [comment]
在react函数组件中将函数以组件标签的形式引用，react diff会在每次计算时都将其做为新标签重新渲染  这个没办法解决 如果要像例子2那么用 将Body单独提取成一个组件即可
`import React from 'react'
import ReactDOM from 'react-dom'
import { Button, Modal, Input } from '@kdcloudjs/kdesign'
const Body = () => {
  const [value, setValue] = React.useState('')
  return <Input value={value} onChange={(e) => setValue(e.target.value)} />
}

function Demo() {
  const bodyStyle = {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }
  const [visible, setVisible] = React.useState(false)
  const handleClick = (bool) => {
    setVisible(bool)
  }

  return (
    <div className={'test_container'}>
      <Button
        onClick={() => {
          handleClick(true)
        }}>
        基础弹出框
      </Button>
      <Modal
        // 若是这样传，输入框每次输入都会失焦，猜测是整个 Body 组件被重新渲染了
        body={<Body />}
        bodyStyle={bodyStyle}
        title="Basic Modal"
        closable={true}
        onCancel={() => handleClick(false)}
        onOk={() => handleClick(false)}
        mask={true}
        visible={visible}
      />
    </div>
  )
}

ReactDOM.render(<Demo />, mountNode)`

**Comment by zzkkui** [comment]
如果当做函数组件来说，确实是要放组件外面，如果只是普通函数返回 jsx ，则可以 使用 body() 这样
