### ISSUE TITLE
table表格带有复选框的时候，鼠标hover上去会有hover类，鼠标在此点击当前行，hover类消失

### ISSUE THREAD

**Issue by NGyc** [kdcloudone/kdesign#350]
## 重现问题步骤
table表格带有复选框的时候，鼠标hover上去会有hover类，鼠标在此点击当前行，hover类消失
![image](https://github.com/kdcloudone/kdesign/assets/23099333/c611c467-03b6-4630-8239-2978dfe8d7d1)
## 实际的结果是什么
希望hover类消失不要消失

**Comment by murisans** [comment]
Bug解决方案： a41_cellSpanWithSelect 鼠标事件选用onMouseEnter,点击是触发点击事件后不会再触发鼠标进入事件； 改用onMouseOver， 点击触发后 鼠标仍在原地，会继续触发mouseOver事件

**Comment by murisans** [comment]
> 点击复选框的时候还是会出现hover类消失的情况

react 有啥好的调试技巧吗， 找半天也不知道row-hover是怎么被移除的 

还有些断点跟踪的代码 源码里面都搜不到，也是用了onMouseEnter，也不知道有没有关系
<img width="1059" alt="image" src="https://github.com/kdcloudone/kdesign/assets/57647858/f92b53e3-86c7-41e5-81f0-361aa6e71086">

**Comment by NGyc** [comment]
应该看看他的highlight这个类是怎么加进去的，是这个类把row-hover给替换了

**Comment by murisans** [comment]
@kdcloudjs/table/es/table/pipeline/features/mergeCellHover.js
![image](https://github.com/kdcloudone/kdesign/assets/57647858/e4a3e267-354d-4996-b1d1-6708bf55bcc7)
mergeCellHover.js 也使用了onMouseEnter监听鼠标事件
但是该文件实现这本仓库不存在

**Comment by murisans** [comment]
> 应该看看他的highlight这个类是怎么加进去的，是这个类把row-hover给替换了

mergeCellHover 是不是修改一下鼠标的监听事件 改成onMouseOver ，也能满足需求了 ， 本来hover 用 mouseEnter也不太合理嘛， 单击鼠标后又不会再触发mouseEnter

**Comment by murisans** [comment]
> 应该看看他的highlight这个类是怎么加进去的，是这个类把row-hover给替换了
通过multiSelect.js 添加highlight类
![image](https://github.com/kdcloudone/kdesign/assets/57647858/7c9edd89-152e-4483-8cd3-0d6defa3a49c)
但是只是pipeline中的其中一个环节 ，具体为什么会把row-hover替换掉，会不会和pipeline有关
![image](https://github.com/kdcloudone/kdesign/assets/57647858/4c721484-6900-4c12-958d-3b6571c2e356)

**Comment by murisans** [comment]
@NGyc  mergeCellProps.js 取不到行原本的class值，导致class丢失了 row-hover
createRowPropsGetter返回的对象里面默认带上className，'className': 'row-hover'
![image](https://github.com/kdcloudone/kdesign/assets/57647858/0dda4c79-db11-40f9-839c-d72bd5f795b9)
PR #357 有更新，你测试一下能不能满足需求

**Comment by wqhui** [comment]
这个初步分析是`row-hover`没有状态存储，行节点更新之后又不会重新触发`enter`事件，导致样式丢了，我们这边会看下怎么完善

**Comment by murisans** [comment]
> 这个初步分析是`row-hover`没有状态存储，行节点更新之后又不会重新触发`enter`事件，导致样式丢了，我们这边会看下怎么完善

最好能在Table组件内部解决掉， 调用方去处理确实很奇怪

**Comment by murisans** [comment]
> @kdcloudjs/table/es/table/pipeline/features/mergeCellHover.js ![image](https://user-images.githubusercontent.com/57647858/239425138-e4a3e267-354d-4996-b1d1-6708bf55bcc7.png) mergeCellHover.js 也使用了onMouseEnter监听鼠标事件 但是该文件实现这本仓库不存在

@wqhui mergeCellHover 使用onMouseEnter去监听是不是不太合理

**Comment by murisans** [comment]
@wqhui  a41_cellSpanWithSelect.md 合并行鼠标悬浮效果联动 这个feature不做到组件内部吗？ 在markdown里面改感觉 又改不全

**Comment by wqhui** [comment]
@murisans mergeCellHover只是为了处理合并单元格则所有融合行的悬浮状态，未考虑到这个功能是提供的`row-hover`的使用问题，之前都是统一使用`tr:hover`去设置悬浮状态，从而避免了数据的存储，这个我们这边需要再讨论看看。

a41_cellSpanWithSelect这个不做到组件内部，是参考其他主流的开源库也都不会处理融合行的悬浮同步。
