### ISSUE TITLE
本地启动项目，docs-search 匹配结果url主站为 react.kingdee.design,不是localhost

### ISSUE THREAD

**Issue by murisans** [kdcloudone/kdesign#359]
## 重现问题步骤

![image](https://github.com/kdcloudone/kdesign/assets/57647858/f78e8c6a-bc39-422c-89a0-7ce3329e70f2)

![image](https://github.com/kdcloudone/kdesign/assets/57647858/671fae32-3aca-45b3-afc0-9b5a4ab80454)

**Comment by IrvingOS** [comment]
当前文档的搜索是使用了一个叫 [algolia](https://www.algolia.com/) 的全文搜索工具，该工具的原理是通过爬取文档的官网 react.kingdee.design 建立索引，在本地输入内容时，也是联网调用 algolia 的接口，其返回的数据为其爬取的官网数据而不是 localhost。

**Comment by murisans** [comment]
> 当前文档的搜索是使用了一个叫 [algolia](https://www.algolia.com/) 的全文搜索工具，该工具的原理是通过爬取文档的官网 react.kingdee.design 建立索引，在本地输入内容时，也是联网调用 algolia 的接口，其返回的数据为其爬取的官网数据而不是 localhost。

本地想用搜索的时候很麻烦，每次都跳到react.kingdee.design去了， 能不能用location.href 处理成相对当前站点跳转的方式吖

**Comment by murisans** [comment]
thumbtack/thumbprint#338

**Comment by murisans** [comment]
<img width="1599" alt="image" src="https://github.com/kdcloudone/kdesign/assets/57647858/6c465d96-a36d-4f44-ab94-5b8c0bc13f2e">
参照DocSearch的设计，提供transformData方法对hits做前处理，开发环境下domain替换为 localhost

**Comment by IrvingOS** [comment]
DocsSearch 有一个移动端的适配组件：MDocsSearch

**Comment by murisans** [comment]
> DocsSearch 有一个移动端的适配组件：MDocsSearch

![image](https://github.com/kdcloudone/kdesign/assets/57647858/6a8e0684-95d9-481e-b81c-4dc9f92f9527)
对比了一下 两个组件的实现 基本一致
setResList前缺少对hits数据的前处理方法, 组件提供transformData方法注入点后 就可以根据环境切换主站了
![image](https://github.com/kdcloudone/kdesign/assets/57647858/73628fa0-36ff-467d-8a0e-0c6fcb69cc39)
