### ISSUE TITLE
[doc][anchor] 纵向锚点固定时，往下滑动 ,导航背景透明与内容重叠，可读性很差,建议添加底色

### ISSUE THREAD

**Issue by murisans** [kdcloudone/kdesign#360]
## 重现链接或代码
https://react.kingdee.design/components/anchor
![image](https://github.com/kdcloudone/kdesign/assets/57647858/82979cea-fe9f-49cb-857c-5dbed65aa93e)

## 期望的结果是什么

纵向锚点导航背景透明，建议添加底色

**Comment by murisans** [comment]
@albyben 尝试添加底色, 发现纵向锚点的z轴高度并不是所有元素最高， 固定锚点后会导致显示被其他元素覆盖。锚点如果固定后应当置顶，这是否算bug？ 
![image](https://github.com/kdcloudone/kdesign/assets/57647858/ea6367b0-7ee2-44b4-a7d3-dec9235af7ef)

![image](https://github.com/kdcloudone/kdesign/assets/57647858/74e33112-aa53-4b5a-9b10-3e636c245682)

**Comment by albyben** [comment]
见commit,已处理。 (6c11626)[https://github.com/kobehhh/kdesign/commit/6c11626bf07697db860cbfbeaa6496010eeb39fd]
