### ISSUE TITLE
[bug][pagination] 简单分页下 分割斜杠 / 到左输入框 和 右面的总页数padding 太小，看起来很挤， 排版不佳

### ISSUE THREAD

**Issue by murisans** [kdcloudone/kdesign#389]
## 重现链接或代码
https://react.kingdee.design/components/pagination
简单分页下 分割斜杠 / 到左输入框 和 右面的总页数距离不等, 排版不佳
![image](https://github.com/kdcloudone/kdesign/assets/57647858/7fbe0de5-52b6-472f-bec6-a90d2109065d)

**Comment by albyben** [comment]
目前已定稿视觉样式，暂不做更新
