### ISSUE TITLE
[Select]选择器期望添加focus方法，

### ISSUE THREAD

**Issue by huangwei9527** [kdcloudone/kdesign#429]
## 重现链接或代码

![image](https://github.com/kdcloudone/kdesign/assets/18244110/1c6b31d5-75ed-435e-82c4-079f0f379f97)

**Comment by kobehhh** [comment]
目前select ref已提供出去 对应的是dom元素，现如果改成提供出去foucs等方法 可能会导致前面使用了ref的报错
如果这个方法没这么必要的话 可以你那边通过拿到input元素去控制focus

**Comment by huangwei9527** [comment]
> 目前select ref已提供出去 对应的是dom元素，现如果改成提供出去foucs等方法 可能会导致前面使用了ref的报错 如果这个方法没这么必要的话 可以你那边通过拿到input元素去控制focus

目前用的1.7.15 Select组件ref上没有select(）方法。调用报错

**Comment by kobehhh** [comment]
ref对应的dom是select最外层的div，不是input 如果要拿input还要再往下层找

**Comment by huangwei9527** [comment]
> ref对应的dom是select最外层的div，不是input 如果要拿input还要再往下层找

ok
