### ISSUE TITLE
[inputNumber] 传入的值为数字时报错

### ISSUE THREAD

**Issue by kobehhh** [kdcloudone/kdesign#430]
## 重现链接或代码
![image](https://github.com/kdcloudone/kdesign/assets/33951750/e1b9108d-2e9f-4d03-a4bf-db7c8a0d788d)
![image](https://github.com/kdcloudone/kdesign/assets/33951750/62c2249a-eb46-4efc-b113-d04694dd9943)

**Comment by murisans** [comment]
![image](https://github.com/kdcloudone/kdesign/assets/57647858/44cc0944-7a2c-4eb4-b2b4-e09ac19d94a8)
API支持value为number, 是否将number转换成string类型处理
