### ISSUE TITLE
点击DropDown，webpack-dev-server提示超出ResizeObserver循环限制

### ISSUE THREAD

**Issue by cecilyu2018** [kdcloudone/kdesign#473]
## 重现链接或代码
![image](https://github.com/kdcloudone/kdesign/assets/45186929/d7580e6e-69a9-430f-a08d-99db25a05e08)
```
<Dropdown menu={menuItems} arrow trigger='click'>
        <span style={{ lineHeight: '24px' }}>
          {store.user.avatar && (
            <UserImg
              className={classNames({ none: defaultAvatar })}
              alt='头像'
              src={store.user.avatar}
              onLoad={() => setDefaultAvatar(false)}
            />
          )}
          {defaultAvatar && <Icon type='avatar-solid' />}
        </span>
      </Dropdown>
```

## 重现问题步骤
本地开发开启webpak-dev-server错误提示，点击Dropdown

## 期望的结果是什么
正常展示下拉框

## 实际的结果是什么
webpak-dev-server提示一个页面渲染错误

## 组件库版本号、浏览器信息
chrome 94.0.4606.81
kdesign@1.7.16
react@17.0.2
webpack@5.88.1
webpack-dev-server@4.15.1

**Comment by hxh2010** [comment]
可通过配置webpack 或 设置监听函数，忽略此错误，[参考链接](https://stackoverflow.com/questions/75774800/how-to-stop-resizeobserver-loop-limit-exceeded-error-from-appearing-in-react-a)
