### ISSUE TITLE
[table]合并行之后大数据量采用虚拟滚动表格会出现展示问题

### ISSUE THREAD

**Issue by wdq1373771482** [kdcloudone/kdesign#527]
## 重现链接或代码
```
import React from 'react'
import ReactDOM from 'react-dom'
import { Table } from '@kdcloudjs/kdesign'

function Demo() {
  const data = React.useMemo(() => (
    Array.from(Array(100000)).map((item, index) => (
      {
        "id": index, 
        "No":index,
        "order":"AP-202009-0000"+index,"from":"陕西环宇科技","to":"深圳环球科技","amount":"26,800.00","balance":"5,200.00"
      }
    ))
  ), [])

  const columns = [  
  { code: 'No', name: '序号', width: 60, align: 'center' },
    { code: 'order', name: '单据号', width: 200, getCellProps: () => { return { rowSpan: 10 } } },
    { code: 'from', name: '来户', width: 200, getCellProps: () => { return { rowSpan: 10 } }  },
    { code: 'to', name: '往户', width: 200 },
    { code: 'amount', name: '应付金额', width: 100, align: 'right' },
    { code: 'balance', name: '应收余额', width: 100, align: 'right' }
  ]

  return (
    <div style={{ marginRight: 12 }}>
      <Table
      style={{ height: 600, width: 800, overflow: 'auto' }}
      isLoading={false}
      dataSource={data}
      columns={columns}
      />
    </div>
  )
}

ReactDOM.render(<Demo />, mountNode)
```

**Comment by albyben** [comment]
原计划的效果是0-9行合并，在单据列合并。滚动后，单据行得内容从AP-202009-00000挨个增加，合并行也显示异常

**Comment by xiaolinsq** [comment]
Demo 写法有问题，每个单元格的rowSpan 都返回10肯定是不对的，如果想要每10个合并可以试试这样写：
`
getCellProps: (value, record, rowIndex) => {
       const rowSpan = 10 - rowIndex % 10
       return { rowSpan }
      } 
`

**Comment by albyben** [comment]
@wdq1373771482  看看满不满足要求，可以的话我就close掉了

**Comment by wdq1373771482** [comment]
项目里的是这样写的  
getCellProps: (value, record, rowIndex) => {  return { rowSpan: record?.length } }
这样的要怎么写 rowSpan

**Comment by wdq1373771482** [comment]
> Demo 写法有问题，每个单元格的rowSpan 都返回10肯定是不对的，如果想要每10个合并可以试试这样写： `getCellProps: (value, record, rowIndex) => { const rowSpan = 10 - rowIndex % 10 return { rowSpan } } `

我在自己项目里试了，如果合并行数固定的话，按照你的写法没问题，如果是上一条我回复的那样子去写，就有问题

**Comment by xiaolinsq** [comment]
合并行rowSpan正确的调用方式都是一个递减的数列，你项目不是一个正确的写法。举个例子，第一行是rowSpan为5，第二行rowSpan为10，第一行设置rowSpan为5期望的是1到5行的单元格合并，第二行设置rowSpan为10期望的是2到11行合并，这样是冲突没有意义的。

**Comment by wdq1373771482** [comment]
> 合并行rowSpan正确的调用方式都是一个递减的数列，你项目不是一个正确的写法。举个例子，第一行是rowSpan为5，第二行rowSpan为10，第一行设置rowSpan为5期望的是1到5行的单元格合并，第二行设置rowSpan为10期望的是2到11行合并，这样是冲突没有意义的。

getCellProps: (value, record, rowIndex) => { return { rowSpan: record?.length } }  那这种的要怎么处理

**Comment by xiaolinsq** [comment]
根据实际场景算出record.length，数据都是你自己决定的
